### PR TITLE
allow setting master shard through ENV['SHARD'] or config/shards.yml

### PR DESCRIPTION
**Pull request by odedniv**
This allows:
- Using ```db:schema:load``` to initialize a new shard (previously it just loaded to whatever was in ```config/database.yml```).
- Having ```config/shards.yml``` your main configuration file for databases. You still need ```config/databases.yml``` for startup, but afterwards all queries go to your main shard.

### CODE REVIEW

**Comment by velles** [comment]
@odedniv are you planning on merging this pull soon. I am experiencing the same original issue. Thanks.

**Comment by odedniv** [comment]
@velles only repository maintainers can merge pull requests, so this is basically waiting on @tchandy when he has time. Good luck

**Comment by sobrinho** [comment]
@odedniv why you want to change the master shard and not change the database at `config/database.yml`?

**Comment by sobrinho** [comment]
Better saying, why your master shard isn't your database at config/database.yml?

**Comment by odedniv** [comment]
@sobrinho It was a long time ago (at a job I'm no longer at), but I believe I wanted the shard name to be meaningful, especially when it's reflected in other tables in the database (like a user table with a "shard" column to know where to look for the user's data).

For example if you have a us shard and a europe shard, who's to say which is master? "master" is only meaningful for rails startup, because it needs some (random/general?) database to connect to in order to describe the models. At first I used the [&/* reference syntax](https://en.wikipedia.org/wiki/YAML#References) to define my names and then set master to duplicate one of them. The problem there was that iterating over the shards (such as in migrations, seeds, and other custom per-shard logic) would run over one of the shards twice.

Does all this make sense?

**Comment by odedniv** [comment]
Also, it seems that others wanted this change as well (@velles) so I guess it might makes sense for more reasons :smile: (or maybe he has the same reason).

**Comment by sobrinho** [comment]
I think we can remove the `ENV['SHARD']` from the source and use a config like this:

``` yaml
octopus:
  master_shard: <%= ENV['SHARD'] %>
```

Because SHARD can be meaningful for other purposes on the environment, or at least use OCTOPUS_MASTER_SHARD, although I prefer the first one.

The pull request needs to be rebased again since recent changes on master, can you do that again? <3

**Comment by odedniv** [comment]
My yearly duties are complete :tongue: 

Not sure why travis is taking so long though.

**Comment by sobrinho** [comment]
The build is broken due to another change, I'll merge and fix the failing spec later, thanks s2

**Pull request merged**
