### PR TITLE
Get rid of ActiveRecord extensions to minimize constant cache invalidation

### PR DESCRIPTION
**Pull request by nickmarden**
This is intended to be a fix for https://github.com/thiagopradi/octopus/issues/280

### CODE REVIEW

**Comment by anhkind** [comment]
@jcoleman your fix is great :+1:

**Comment by jcoleman** [comment]
@nickmarden Any timeline on this?

**Comment by nickmarden** [comment]
@jcoleman I've assigned it to @thiagopradi so that he can take a look. I think the PR is safe, but I want one other set of eyeballs to look at it. If it languishes I'll decide whether to make an executive decision and merge it on my own. Sorry for the delay!

**Comment by nickmarden** [comment]
OK @thiagopradi since this is passing CI and lots of people are clamoring for it, I'mma merge and you can hit me with a frying pan if you think that was the wrong thing to do.

**Comment by ccocchi** [comment]
When can we expect a new release with recent changes? :)

**Comment by nickmarden** [comment]
@ccocchi I have pushed ar-octopus 0.8.6 built from a138b93

**Comment by anhkind** [comment]
@nickmarden  :+1:

**Comment by ccocchi** [comment]
Awesome thanks !

**Pull request merged**
