### PR TITLE
Fix Active Record sum

### PR DESCRIPTION
**Pull request by SixiS**

### CODE REVIEW

**Comment by sekiyama58** [comment]
Thanks to pointing out this. It seems I was misunderstanding something about specification of `sum` method.

To use ActiveRecord's `sum` method, `:sum` should be completely removed from `ENUM_METHODS` explicitly, like:
```
    ENUM_METHODS = (::Enumerable.instance_methods - ::Object.instance_methods).\
reject do |m|
      ::ActiveRecord::Relation.instance_method(m).source_location rescue nil
    end + [:each, :map, :index_by] - [:sum]
```

In addition, all the test for `sum` in `spec/octopus/association_shard_tracking_spec.rb` should be changed from
```
... .sum(&:id)
```

to

```
... .sum(:id)
```

**Comment by SixiS** [comment]
@sekiyama58 - Thanks for the response!

I don't think it is necessary to `- [:sum]`
It is removed by the `::ActiveRecord::Relation.instance_method(m).source_location rescue nil` line.

Also I think it is ok to keep it in `ENUM_WITH_BLOCK_METHODS`, along with the tests.

If you passed a block to `sum` like 
```
... .sum(&:id)
```

You would want to use the Enumerable method, not the ActiveRecord one.

**Comment by sekiyama58** [comment]
Please see https://github.com/thiagopradi/octopus/pull/499 to fix travis CI.
It is caused by recent update of `mysql2` gem version specification: https://github.com/thiagopradi/octopus/commit/d87f5996cd359f5349b3d4a7e8e18af56dc6d5fb#diff-65b23e9afac9ad2ca203fbbbeaac816cR30

**Comment by sekiyama58** [comment]
@thiagopradi Could you merge this PR? (CI failure is due to `mysql2` version specification which is not compatible with old Rails 4.0/4.1, so please don't care).

**Comment by thiagopradi** [comment]
@sekiyama58 @SixiS - merged, thanks!

**Pull request merged**
