### PR TITLE
Add Rails 5 beta 3 to appraisals

### PR DESCRIPTION
**Pull request by treble37**
- Adding Rails 5 support

### CODE REVIEW

**Comment by treble37** [comment]
Along the lines of this PR https://github.com/thiagopradi/octopus/issues/249

**Comment by serggl** [comment]
`alias_method_chain` deprecation warning was not fixed with this PR

**Comment by Fuffi** [comment]
So, no Rails5 support?

**Comment by thiagopradi** [comment]
Rails 5 support was merged to master, so closing this PR.

**Pull request closed without merging**
