### PR TITLE
Rails 5.2 Support

### PR DESCRIPTION
**Pull request by thiagopradi**
Hi Folks,

This is the base branch for Rails 5.2, along with some code cleanups. I've dropped support for two old Rails versions (4.0 and 4.1), and centralized all patches for Rails 5.2 support.

Thiago

### CODE REVIEW

**Comment by king601** [comment]
Thanks for your work on this upgrade, I just started my work's upgrade to 5.2 and ran into issues, so I'm thankful to see this support!

**Comment by PhilCoggins** [comment]
Hi @thiagopradi 👋 . We're looking to upgrade our production environment to Rails 5.2. I've suggested that we wait until we have a stable release for this gem. Is there a timeframe for this release? Can we offer any help? Thanks!

**Comment by PhilCoggins** [comment]
FWIW I can get specs up and running with the following:

```
```

**Comment by PhilCoggins** [comment]
FWIW I can get specs running with the following:

```
$ git diff
diff --git a/Rakefile b/Rakefile
index 814c091..ec42ef2 100644
--- a/Rakefile
+++ b/Rakefile
@@ -64,7 +64,7 @@ namespace :db do
       # the model be a descendent of ActiveRecord::Base.
       class BlankModel < ActiveRecord::Base; end
 
-      BlankModel.using(shard_symbol).connection.initialize_schema_migrations_table
+      BlankModel.using(shard_symbol).connection.transaction { ActiveRecord::SchemaMigration.create_table }
```

This method was [removed](https://github.com/rails/rails/pull/27740) in Rails 5.2.

`.arel_engine` was also [removed](https://github.com/rails/rails/pull/29825/files) from AR core, so the following fixes `model_spec`:
```
$ git diff
diff --git a/spec/octopus/model_spec.rb b/spec/octopus/model_spec.rb
index bdfeb6f..a4acec4 100644
--- a/spec/octopus/model_spec.rb
+++ b/spec/octopus/model_spec.rb
@@ -306,8 +306,8 @@ describe Octopus::Model do
 
   describe 'using a postgresql shard' do
     it 'should update the Arel Engine' do
-      expect(User.using(:postgresql_shard).arel_engine.connection.adapter_name).to eq('PostgreSQL')
-      expect(User.using(:alone_shard).arel_engine.connection.adapter_name).to eq('Mysql2')
+      expect(User.using(:postgresql_shard).connection.adapter_name).to eq('PostgreSQL')
+      expect(User.using(:alone_shard).connection.adapter_name).to eq('Mysql2')
     end
```

This makes all specs green for me, though when I run all specs together, I do get:
```
     Mysql2::Error:
       Too many connections
```
I'm not sure if this is a local environment issue (I don't use MySQL), but might want to be checked out.

Lastly, there's a few other places where the `initialize_schema_migrations_table` method needs to be removed. Hopefully this helps move things along!

**Comment by Stuart-Johnson** [comment]
@thiagopradi Also looking to upgrade to rails 5.2, and this gem is holding us up, and the 5.2 upgrade itself is holding up several other gem updates, so this is really a roadblock for us.

Any timeframe for this branch being finished? Looks like 3 months since the last commit... Is this gem abandoned?

**Comment by pboling** [comment]
@Stuart-Johnson @PhilCoggins @king601 Please refer to https://github.com/thiagopradi/octopus/issues/490 regarding the question of the status of this gem.  @thiagopradi doesn't really use the gem any more himself.  More assistance is required to get 5.2 support out the door!  Please pick up the ball and run with it if you have bandwidth.

**Comment by kevinjcoleman** [comment]
@king601 @PhilCoggins @pboling @Stuart-Johnson I got things working on this PR https://github.com/thiagopradi/octopus/pull/507, passing specs and everything. Not sure if I'm missing something there though.

**Comment by thiagopradi** [comment]
@king601 @PhilCoggins @pboling @Stuart-Johnson @kevinjcoleman  - It seems like all tests are green with Rails 5.2. Can any of you do a double check on this branch to make sure it works on a real Rails 5.2 app? If it works, I'll release a new version this week with Rails 5.2 support.

**Comment by king601** [comment]
I haven't been able to get a chance to test this week, but previously the issues I had were related to not having a shards.yml file, it seemed like something changed where previously we could avoid needing to make a shards file, but the easy fix was just to make a shards file locally for development/test.

Not sure if I'll get a chance to test with our app this week, it's been a busy week for me here.

**Comment by kevinjcoleman** [comment]
@thiagopradi everything has been working well for me this week!

**Comment by thiagopradi** [comment]
@kevinjcoleman - cool! Thanks for the feedback. Merging & closing this thread.

**Comment by thiagopradi** [comment]
@king601 @PhilCoggins @pboling @Stuart-Johnson @kevinjcoleman a new version of Octopus with support for Rails 5.2 has been released. thanks for all your hard work.

**Comment by micahbf** [comment]
A huge thank you to @thiagopradi and everyone who has been involved in developing and testing this release!

**Pull request merged**
