### PR TITLE
Rails 5 compatibility

### PR DESCRIPTION
**Pull request by zillou**
Failing Specs:

- [x] should respond  respond_to?(:pk_and_sequence_for)  

    `pk_and_sequence_for` is removed in Rails5 MySQL adapter  https://github.com/rails/rails/pull/21686

- [ ] `decrement!` and `increment!`

    https://github.com/rails/rails/pull/11410

### CODE REVIEW

**Comment by serggl** [comment]
`alias_method_chain` deprecation warning was not fixed with this PR

**Comment by zillou** [comment]
@lex148 There are still some failing specs, please refer to the Travis CI build.

**Comment by thiagopradi** [comment]
@zillou and @lex148 - thanks for your work on this PR. I'm closing it in favor of https://github.com/thiagopradi/octopus/tree/octopus_09 - which contains all the fixes for Rails 5.

**Comment by isaacseymour** [comment]
Hey @thiagopradi - is there a schedule for when to expect a new version with all the changes on that branch?

**Comment by thiagopradi** [comment]
@isaacseymour - I hope to release it next week.

**Pull request closed without merging**
